services:
  alerts:
    path: src/services/alerts
  dashboard:
    path: src/services/dashboard
  connector:
    path: src/services/connector
    params:
      ecsFailureTopicArn: ${alerts.ECSFailureTopicArn}
