name: Security Hub Sync

on:
  schedule:
    - cron: "0 0 * * *" # At 12am everyday
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-group

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ github.ref_name }}
    env:
      STAGE_NAME: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Validate stage name
        run: |
          if [[ ! $STAGE_NAME =~ ^[a-z][a-z0-9-]*$ ]]; then
              echo "ERROR:  Your branch name, $STAGE_NAME, is not a valid Serverless Framework stage name." && exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Node cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ github.workflow}}-${{ github.job }}${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800
      - name: Sync Security Hub Findings
        run: run syncSecurityHubFindings --auth ${{ env.auth }} --repository Enterprise-CMCS/${{ github.event.repository.name }} --accountNickname $STAGE_NAME
        env:
          auth: ${{ secrets.GITHUB_TOKEN }}
