name: Test Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: install
        run: |
          if [ ! -d "node_modules" ]; then # If we don't have any node_modules (CircleCI cache miss scenario), run yarn install --frozen-lockfile.  Otherwise, we're all set, do nothing.
            yarn install --frozen-lockfile
          fi
      - run: yarn run coverage
      - name: publish test coverage to code climate
        if: always() && env.CC_TEST_REPORTER_ID != ''
        uses: paambaati/codeclimate-action@v2.7.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
